// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCe7t9w9oGPK74rNw0z0JDSIYZZASsOzeY",
      authDomain: "eeew-71b1d.firebaseapp.com",
      databaseURL: "https://eeew-71b1d-default-rtdb.firebaseio.com",
      projectId: "eeew-71b1d",
      storageBucket: "eeew-71b1d.appspot.com",
      messagingSenderId: "758808618040",
      appId: "1:758808618040:web:6765e8d682b42be56132cd",
      measurementId: "G-2YRFXWWCN3"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
    storageBucket: '',
  );
//
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
    storageBucket: '',
    iosClientId:
        '',
    iosBundleId: '',
  );
// // <<<<<<< HEAD
//
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
    storageBucket: '',
    iosClientId:
        '',
    iosBundleId: '',
  );
// =======
// >>>>>>> 3dafcf32f1f75abbac55360c5db7324558663c69
}
