name: sample_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  mongo_dart: ^0.7.4+1
    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.3
    #  google_fonts: ^3.0.1
  animated_splash_screen: ^1.1.0
  firebase_auth: ^3.6.2
  firebase_core: ^1.20.0
  random_password_generator: ^0.2.1
  cloud_firestore: ^3.4.5
  flutter_email_sender: ^5.1.0
  path_provider: ^2.0.11
  dropdown_search: ^5.0.2
  custom_searchable_dropdown:
  textfield_search: ^0.10.0
  flutter_typeahead: ^3.0.0-nullsafety.0
  firestore_search: ^0.1.9
  searchable_dropdown: ^1.1.3

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
